// Real Codex AppServer, real Docker, mTLS facade; deterministic local model only.
import {pngBase64} from './fixture-image.mjs';
import assert from 'node:assert/strict';import {join} from 'node:path';import {mkdtemp,mkdir,rm,readFile,writeFile,realpath} from 'node:fs/promises';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {Bridge} from '../packages/bridge-core/lib/server.mjs';import {init,addProject,invite,configuration,revoke} from '../packages/bridge-core/lib/admin.mjs';import {pairClient,loadClient} from '../packages/bridge-core/lib/client.mjs';import {CodexAdapter} from '../src/codex-adapter.mjs';import {fixtureProvider} from './local-provider.mjs';
const root=await realpath(await mkdtemp(join(tmpdir(),'remotedesk-codex-wire-'))),workspace=join(root,'workspace'),state=join(root,'state');await mkdir(workspace);let mode='text',bridge,releaseModel,steerSeen=false;
const provider=await fixtureProvider(async request=>{steerSeen ||= JSON.stringify(request.input).includes('STEER_FIXTURE');const next=mode;if(next==='hold'){await new Promise(r=>releaseModel=r);mode='text';return{text:'FIRST_STEP_DONE'};}if(next==='hang')return{hang:true};mode='text';if(next==='exec')return{call:{name:'remotedesk_workspace_exec',arguments:{command:"printf 'CODEX_DOCKER_OK' > codex-result.txt; cat codex-result.txt"}}};if(next==='question')return{call:{name:'remotedesk_question',arguments:{question:'Fixture question?'}}};return{text:'CODEX_WIRE_COMPLETE'};});
const waitFor=async fn=>{const until=Date.now()+30000;while(Date.now()<until){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,30));}throw new Error('FIXTURE_WAIT_TIMEOUT');};
try{
 await init(state,{engine:'codex'});await addProject(state,{id:'p',path:workspace,vision:true,image:process.env.REMOTEDESK_TEST_IMAGE});const config=await configuration(state);config.port=0;config.coordinationDirectory=join(root,'locks');await writeFile(join(state,'config.json'),JSON.stringify(config));
 bridge=new Bridge(state,new CodexAdapter({providerOverrides:provider.overrides}));let {address}=await bridge.start();const directory=join(root,'client');await pairClient(directory,{url:`https://127.0.0.1:${address.port}`,invite:await invite(state,{projects:['p']})});const loaded=await loadClient(directory),client=loaded.client;let handshake=loaded.handshake;const call=(method,params,operationId=randomUUID())=>client.write(method,params,{operationId,epoch:handshake.epoch.id});const created=await call('session.create',{projectId:'p'});assert.equal(created.status,'succeeded',JSON.stringify(created));const id=created.result.sessionId;let lease=(await call('lease.acquire',{sessionId:id})).result.lease;const events=[],abort=new AbortController();const stream=client.events({cursor:0,runtime:handshake.runtime,signal:abort.signal,onEvent:e=>events.push(e)}).catch(e=>e);
 const turn=async(next,answer)=>{mode=next;const op=randomUUID(),params={sessionId:id,lease,text:'Wire fixture '+next};const receipt=await call('turn.start',params,op);assert.equal(receipt.status,'succeeded',JSON.stringify(receipt));assert.deepEqual(await call('turn.start',params,op),receipt);if(answer){const pending=await waitFor(async()=> (await client.read('approval.list',{sessionId:id}))[0]);assert.equal((await call('approval.answer',{sessionId:id,lease,approvalId:pending.id,answer})).status,'succeeded');}await waitFor(()=>!bridge.adapter.runs.has(id));};
 await turn('exec',{decision:'accept'});assert.equal(await readFile(join(workspace,'codex-result.txt'),'utf8'),'CODEX_DOCKER_OK');await turn('exec',{decision:'decline'});await turn('question',{text:'CODEX_WIRE_ANSWER'});assert.ok(JSON.stringify(await client.read('session.read',{sessionId:id})).includes('CODEX_WIRE_ANSWER'));
 const upload=await call('attachment.upload',{projectId:'p',mime:'text/plain',data:Buffer.from('TEXT_ATTACHMENT_OK').toString('base64')});assert.equal(upload.status,'succeeded');mode='text';assert.equal((await call('turn.start',{sessionId:id,lease,text:'Attachment fixture',attachments:[upload.result.attachmentId]})).status,'succeeded');await waitFor(()=>!bridge.adapter.runs.has(id));assert.ok(JSON.stringify(await client.read('session.read',{sessionId:id})).includes('TEXT_ATTACHMENT_OK'));
 const imageUpload=await call('attachment.upload',{projectId:'p',mime:'image/png',data:pngBase64});assert.equal(imageUpload.status,'succeeded');mode='text';assert.equal((await call('turn.start',{sessionId:id,lease,text:'Image fixture',attachments:[imageUpload.result.attachmentId]})).status,'succeeded');await waitFor(()=>!bridge.adapter.runs.has(id));assert.ok(provider.calls.at(-1).images>0,'image reaches actual App Server model request');
 mode='hold';await call('turn.start',{sessionId:id,lease,text:'Steering fixture'});await waitFor(()=>releaseModel);assert.equal((await call('turn.steer',{sessionId:id,lease,text:'STEER_FIXTURE'})).status,'succeeded');releaseModel();await waitFor(()=>!bridge.adapter.runs.has(id));assert.ok(steerSeen,'steer reaches the next model step');assert.ok(JSON.stringify(await client.read('session.read',{sessionId:id})).includes('STEER_FIXTURE'));
 mode='hang';await call('turn.start',{sessionId:id,lease,text:'Cancel fixture'});await waitFor(()=>bridge.adapter.runs.get(id)?.turnId);assert.equal((await call('turn.cancel',{sessionId:id,lease})).status,'succeeded');assert.equal((await call('session.archive',{sessionId:id,lease})).status,'succeeded');assert.equal((await call('session.resume',{sessionId:id,lease})).status,'succeeded');await turn('exec',{decision:'accept'});assert.ok(events.some(e=>JSON.stringify(e).includes('CODEX_WIRE_COMPLETE')));abort.abort();await stream;
 // Restart the actual bridge at the same endpoint and reconcile through snapshots.
 config.port=address.port;await writeFile(join(state,'config.json'),JSON.stringify(config));await bridge.stop();bridge=new Bridge(state,new CodexAdapter({providerOverrides:provider.overrides}));await bridge.start();handshake=await client.read('handshake',{version:1});lease=(await call('lease.acquire',{sessionId:id})).result.lease;assert.equal((await call('session.resume',{sessionId:id,lease})).status,'succeeded');await turn('exec',{decision:'accept'});revoke(state,handshake.deviceId);await assert.rejects(client.read('project.list'),/DEVICE_UNAUTHORIZED/);console.log('PASS Codex AppServer + Docker + mTLS: approval, question, attachments, streams, dedup, cancel, archive, full process restart/resume and revoke');
}finally{await bridge?.stop();await provider.close();await rm(root,{recursive:true,force:true});}
