// Real pinned Codex AppServer + deterministic local provider. No paid inference.
import assert from 'node:assert/strict';import {mkdtemp,mkdir,rm,access} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {CodexAdapter} from '../src/codex-adapter.mjs';import {fixtureProvider} from './local-provider.mjs';
const root=await mkdtemp(join(tmpdir(),'remotedesk-codex-runtime-')),path=join(root,'project');await mkdir(path);let mode='text',calls=0,questions=0,doneResolve;const events=[];
const provider=await fixtureProvider(async()=>{const next=mode;if(next==='hang')return{hang:true};mode='text';if(next==='exec')return{call:{name:'remotedesk_workspace_exec',arguments:{command:'printf fixture'}}};if(next==='question')return{call:{name:'remotedesk_question',arguments:{question:'Fixture question?'}}};if(next==='native')return{call:{name:'exec_command',arguments:{cmd:`echo BAD > "${join(root,'escape.txt')}"`,sandbox_permissions:'require_escalated',justification:'Must not execute'}}};return{text:'REMOTE_DESK_FIXTURE_OK'};});
const executor={async recover(){},async check(){},async run(){calls++;return{exitCode:0,stdout:'FIXTURE_EXECUTOR_OK',stderr:''};}};
const binding={projects:[{id:'test',path}],emit:(id,e)=>{events.push(e);if(e.type==='turn/completed')doneResolve?.();},ask:async(id,r)=>{if(r.kind==='question'){questions++;return{text:'FIXTURE_ANSWER'};}return{decision:'accept'};}};
let adapter=new CodexAdapter({providerOverrides:provider.overrides,executor,diagnostic:e=>console.error(JSON.stringify({fixtureRequestError:e}))});
const turn=async next=>{mode=next;const done=new Promise((resolve,reject)=>{doneResolve=resolve;setTimeout(()=>reject(new Error('FIXTURE_TURN_TIMEOUT')),30000).unref();});await adapter.start(s,'Run the fixture.');await done;};const s={id:'test',project:'test'};
try{adapter.bind(binding);await adapter.create(s,{id:'test',path});await turn('text');await turn('exec');assert.equal(calls,1);await turn('question');assert.equal(questions,1);await turn('native');await assert.rejects(access(join(root,'escape.txt')));assert.equal(calls,1);assert.ok(JSON.stringify(events).includes('FIXTURE_EXECUTOR_OK'));
 const forbidden=['exec_command','write_stdin','apply_patch','view_image','request_permissions','shell','shell_command','read_file','list_dir','grep_files','spawn_agent','browser','web_search'];const names=provider.calls.flatMap(c=>c.tools?.map(t=>t.name)??[]);assert.deepEqual([...new Set(names)].sort(),['remotedesk_question','remotedesk_workspace_exec','remotedesk_workspace_read']);assert.deepEqual(names.filter(n=>forbidden.includes(n)),[]);console.log('PASS real Codex empty-environment tool surface, dynamic execution/approval/question, and rejected invented native exec');
 mode='hang';const cancelled=new Promise((resolve,reject)=>{doneResolve=resolve;setTimeout(()=>reject(new Error('CANCEL_TIMEOUT')),15000).unref();});await adapter.start(s,'Cancel this.');await new Promise(r=>setTimeout(r,100));await adapter.cancel(s);await cancelled;await adapter.close();adapter=new CodexAdapter({providerOverrides:provider.overrides,executor,diagnostic:e=>console.error(JSON.stringify({fixtureRequestError:e}))});adapter.bind(binding);await adapter.resume(s);const before=calls;await turn('exec');assert.equal(calls,before+1);assert.ok((await adapter.read(s)).turns.length>0);console.log('PASS real Codex cancel, process restart, transcript and persisted dynamic tools with empty environment reapplied');
}finally{await adapter.close();await provider.close();await rm(root,{recursive:true,force:true});}
